[package]
name = "aoc22-rust"
version = "0.1.0"
edition = "2021"

include = ["**/input.txt"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10"